version: '3'
services:
  application:
    build:
        context: .
        dockerfile: dockerfile
    volumes:
      - .:/awesomeio
    depends_on:
      - database
    ports:
      - "5000:5000"

  database:
    image: mongo:latest
    container_name: "database"
    volumes:
      # - ./data/db:/data/db
      - ./log:/log
    ports:
      - "27017:27017"
    command: mongod --smallfiles 
